import {
    FaPython,
    FaJava,
    FaHtml5,
    FaCss3Alt,
    FaSass,
    FaReact,
    FaVuejs,
    FaAngular,
    FaNodeJs,
    FaPhp,
    FaAws,
    FaGitAlt,
    FaJenkins,
    FaLinux,
    FaDocker,
    FaMicrochip,
} from "react-icons/fa6";
import {
    BiLogoCPlusPlus,
    BiLogoGoLang,
    BiLogoJavascript,
    BiLogoTypescript,
    BiLogoTailwindCss,
    BiLogoRedux,
    BiLogoPostgresql,
    BiLogoGraphql,
    BiLogoMongodb,
    BiLogoSpringBoot,
    BiLogoVisualStudio,
    BiSolidMicrochip,
} from "react-icons/bi";
import {
    SiRuby,
    SiAndroid,
    SiFirebase,
    SiKicad,
    SiAltiumdesigner,
    SiLtspice,
    SiStmicroelectronics,
    SiEspressif,
    SiProteus,
    SiAmd,
    SiAutocad,
} from "react-icons/si";
import { TbMathMaxMin } from "react-icons/tb";
import { GiCircuitry } from "react-icons/gi";
import {
    FcMindMap,
    FcCommandLine,
    FcPicture,
    FcDatabase,
    FcIphone,
    FcElectronics,
    FcCircuit,
    FcDisplay,
    FcSupport,
} from "react-icons/fc";

enum TagTypes {
    Languages = "1",
    FrontEnd = "2",
    BackEnd = "3",
    Mobile = "4",
    Embedded = "5",
    PcbDesign = "6",
    RtlDesign = "7",
    Tools = "8",
}

const tagTypeNames = [
    { icon: <FcMindMap />, label: "All", value: "0" },
    { icon: <FcCommandLine />, label: "Languages", value: TagTypes.Languages },
    { icon: <FcPicture />, label: "Front End", value: TagTypes.FrontEnd },
    { icon: <FcDatabase />, label: "Back End", value: TagTypes.BackEnd },
    { icon: <FcIphone />, label: "Mobile", value: TagTypes.Mobile },
    { icon: <FcElectronics />, label: "Embedded", value: TagTypes.Embedded },
    { icon: <FcCircuit />, label: "PCB Design", value: TagTypes.PcbDesign },
    { icon: <FcDisplay />, label: "RTL Design", value: TagTypes.RtlDesign },
    { icon: <FcSupport />, label: "Tools", value: TagTypes.Tools },
];

const tags = [
    {
        icon: <FaPython color={"#306998"} />,
        text: "Python",
        bgColor: "#ffd43b",
        color: "black",
        filters: [TagTypes.Languages, TagTypes.BackEnd],
    },
    {
        icon: <BiLogoCPlusPlus />,
        text: "C/C++",
        bgColor: "#004482",
        color: "white",
        filters: [TagTypes.Languages, TagTypes.Embedded],
    },
    {
        icon: <FaJava color={"#5382a1"} />,
        text: "Java",
        bgColor: "#f89820",
        color: "black",
        filters: [TagTypes.Languages, TagTypes.BackEnd, TagTypes.Mobile],
    },
    {
        icon: <TbMathMaxMin color={"#e76e38"} />,
        text: "MATLAB",
        bgColor: "#0076a8",
        color: "white",
        filters: [TagTypes.Languages, TagTypes.Tools],
    },
    {
        icon: <SiRuby />,
        text: "Ruby",
        bgColor: "#d51f06", // lighter: #de3f24, darker: #d51f06
        color: "white",
        filters: [TagTypes.Languages, TagTypes.BackEnd],
    },
    {
        icon: <BiLogoGoLang />,
        text: "Go",
        bgColor: "#00ADD8",
        color: "white",
        filters: [TagTypes.Languages, TagTypes.BackEnd],
    },
    {
        icon: <BiLogoJavascript />,
        text: "JavaScript",
        bgColor: "#f0db4f",
        color: "#323330",
        filters: [TagTypes.Languages, TagTypes.FrontEnd, TagTypes.BackEnd, TagTypes.Mobile],
    },
    {
        icon: <BiLogoTypescript />,
        text: "TypeScript",
        bgColor: "#3178c6",
        color: "white",
        filters: [TagTypes.Languages, TagTypes.FrontEnd, TagTypes.BackEnd, TagTypes.Mobile],
    },
    {
        icon: <FaHtml5 />,
        text: "HTML",
        bgColor: "#e34c26",
        color: "white",
        filters: [TagTypes.FrontEnd],
    },
    {
        icon: <FaCss3Alt />,
        text: "CSS",
        bgColor: "#264de4",
        color: "white",
        filters: [TagTypes.FrontEnd],
    },
    {
        icon: <FaSass />,
        text: "Sass/SCSS",
        bgColor: "#cd6799",
        color: "white",
        filters: [TagTypes.FrontEnd],
    },
    {
        icon: <FaReact />,
        text: "React",
        bgColor: "#06bcee",
        color: "#20232a",
        filters: [TagTypes.FrontEnd],
    },
    {
        icon: <FaVuejs color={"#34495e"} />,
        text: "Vue",
        bgColor: "#41b883",
        color: "white",
        filters: [TagTypes.FrontEnd],
    },
    {
        icon: <FaAngular />,
        text: "Angular",
        bgColor: "#c3002f",
        color: "white",
        filters: [TagTypes.FrontEnd],
    },
    {
        icon: <BiLogoTailwindCss />,
        text: "Tailwind CSS",
        bgColor: "#06b6d4",
        color: "white",
        filters: [TagTypes.FrontEnd],
    },
    {
        icon: <BiLogoRedux />,
        text: "Redux",
        bgColor: "#764abc",
        color: "white",
        filters: [TagTypes.FrontEnd],
    },
    {
        icon: <SiAndroid />,
        text: "Android",
        bgColor: "#32de84",
        color: "black",
        filters: [TagTypes.Mobile, TagTypes.Tools],
    },
    {
        icon: <FaReact />,
        text: "React Native",
        bgColor: "#06bcee",
        color: "#20232a",
        filters: [TagTypes.Mobile],
    },
    {
        icon: <FaNodeJs />,
        text: "Node.js",
        bgColor: "#3c873a",
        color: "white",
        filters: [TagTypes.FrontEnd, TagTypes.BackEnd],
    },
    {
        icon: <FaPhp />,
        text: "PHP",
        bgColor: "#777bb3",
        color: "black",
        filters: [TagTypes.Languages, TagTypes.BackEnd],
    },
    {
        icon: <BiLogoPostgresql />,
        text: "PosgreSQL",
        bgColor: "#336791",
        color: "white",
        filters: [TagTypes.BackEnd],
    },
    {
        icon: <BiLogoGraphql />,
        text: "GraphQL",
        bgColor: "#e10098",
        color: "white",
        filters: [TagTypes.BackEnd],
    },
    {
        icon: <SiFirebase />,
        text: "Firebase",
        bgColor: "#ff9100",
        color: "black",
        filters: [TagTypes.BackEnd],
    },
    {
        icon: <BiLogoMongodb />,
        text: "MongoDB",
        bgColor: "#00684a",
        color: "white",
        filters: [TagTypes.BackEnd],
    },
    {
        icon: <BiLogoSpringBoot />,
        text: "Spring",
        bgColor: "#6db33f",
        color: "white",
        filters: [TagTypes.BackEnd],
    },
    {
        icon: <FaAws />,
        text: "AWS",
        bgColor: "#ff9900",
        color: "black",
        filters: [TagTypes.BackEnd, TagTypes.Tools],
    },
    {
        icon: <FaGitAlt />,
        text: "Git",
        bgColor: "#f34f29",
        color: "white",
        filters: [TagTypes.Tools],
    },
    {
        icon: <FaJenkins />,
        text: "Jenkins",
        bgColor: "#f0d6b7",
        color: "black",
        filters: [TagTypes.Tools],
    },
    {
        icon: <FaLinux />,
        text: "Linux",
        bgColor: "white",
        color: "black",
        filters: [TagTypes.Tools],
    },
    {
        icon: <FaDocker />,
        text: "Docker",
        bgColor: "#1d63ed",
        color: "white",
        filters: [TagTypes.Tools],
    },
    {
        icon: <BiLogoVisualStudio />,
        text: "VS Code",
        bgColor: "#0078d7",
        color: "white",
        filters: [TagTypes.Tools],
    },
    {
        icon: <BiSolidMicrochip />,
        text: "VHDL",
        bgColor: "",
        color: "",
        filters: [TagTypes.Languages, TagTypes.RtlDesign],
    },
    {
        icon: <FaMicrochip />,
        text: "Verilog",
        bgColor: "",
        color: "",
        filters: [TagTypes.Languages, TagTypes.RtlDesign],
    },
    {
        icon: <SiKicad />,
        text: "KiCad",
        bgColor: "#314cb0",
        color: "white",
        filters: [TagTypes.PcbDesign, TagTypes.Tools],
    },
    {
        icon: <SiAltiumdesigner />,
        text: "Altium Designer",
        bgColor: "#d6bc81",
        color: "#3d3d3d",
        filters: [TagTypes.PcbDesign, TagTypes.Tools],
    },
    {
        icon: <SiLtspice />,
        text: "LTspice",
        bgColor: "#910029",
        color: "white",
        filters: [TagTypes.PcbDesign, TagTypes.Tools],
    },
    {
        icon: <GiCircuitry color={"#eb1c2e"} />,
        text: "Cadence",
        bgColor: "white",
        color: "#242021",
        filters: [TagTypes.PcbDesign, TagTypes.Tools],
    },
    {
        icon: <SiStmicroelectronics />,
        text: "STM32",
        bgColor: "#3bb5e8",
        color: "#19233e",
        filters: [TagTypes.Embedded, TagTypes.Tools],
    },
    {
        icon: <SiEspressif />,
        text: "ESP32",
        bgColor: "#e8362d",
        color: "black",
        filters: [TagTypes.Embedded, TagTypes.Tools],
    },
    {
        icon: <SiProteus />,
        text: "Proteus",
        bgColor: "#006074",
        color: "white",
        filters: [TagTypes.RtlDesign, TagTypes.Tools],
    },
    {
        icon: <SiAmd />,
        text: "Vivado",
        bgColor: "#dce04a",
        color: "#6a6a6c",
        filters: [TagTypes.RtlDesign, TagTypes.Tools],
    },
    {
        icon: <SiAutocad />,
        text: "AutoCAD",
        bgColor: "#770829",
        color: "white",
        filters: [TagTypes.Tools],
    },
];

export { tags, TagTypes, tagTypeNames };
