const workData = [
    {
        company: "Silicon Bioelectronics Laboratory",
        position: "Research Assistant",
        duration: "Jan 2024 - Apr 2024",
        description: <></>,
        logo: "",
        blurLogo: "",
        url: "https://uwaterloo.ca/silicon-bioelectronics-laboratory",
        tags: [],
    },
    {
        company: "Silicon Bioelectronics Laboratory",
        position: "Hardware Designer",
        duration: "Sep 2024 - Dec 2024",
        description: <></>,
        logo: "",
        blurLogo: "",
        url: "https://uwaterloo.ca/silicon-bioelectronics-laboratory",
        tags: [],
    },
    {
        company: "Composite Biomaterial Systems Laboratory",
        position: "Research Assistant",
        duration: "May 2023 - Aug 2023",
        description: <></>,
        logo: "",
        blurLogo: "",
        url: "https://uwaterloo.ca/waterloo-composite-biomaterial-systems-lab",
        tags: [],
    },
    {
        company: "Onsemi",
        position: "Hardware & Systems Developer",
        duration: "Jan 2023 - Apr 2023",
        description: <></>,
        logo: "",
        blurLogo: "",
        url: "https://www.onsemi.com",
        tags: [],
    },
    {
        company: "St Michael's Hospital",
        position: "Medical Application Developer",
        duration: "Aug 2021 - Aug 2022",
        description: <></>,
        logo: "",
        blurLogo: "",
        url: "https://unityhealth.to",
        tags: [],
    },
    {
        company: "Composite Biomaterial Systems Laboratory",
        position: "Research Assistant",
        duration: "Jan 2022 - Apr 2022",
        description: <></>,
        logo: "",
        blurLogo: "",
        url: "https://uwaterloo.ca/waterloo-composite-biomaterial-systems-lab",
        tags: [],
    },
    {
        company: "Ford Motor Company",
        position: "Software Developer",
        duration: "Jan 2021 - Apr 2021",
        description: <></>,
        logo: "",
        blurLogo: "",
        url: "https://www.ford.ca",
        tags: [],
    },
    {
        company: "Ford Motor Company",
        position: "Test Automation Developer",
        duration: "May 2020 - Aug 2020",
        description: <></>,
        logo: "",
        blurLogo: "",
        url: "https://www.ford.ca",
        tags: [],
    },
];

export { workData };
